### ISSUE TITLE
Please add an Open Source license to this project

### ISSUE THREAD

**Issue by obscurerichard** [ghewgill/ljdump#3]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://opensource.org/licenses/MIT

(replace the copyright statement with your copyright, of course)

Thank you for making this available. I used this (by downloading and running it unmodified) in this package: https://github.com/obscureorganization/lj2wp

**Comment by ghewgill** [comment]
Fixed in a21fe1259f58301b3494324ef1ae028cf35ab389

**Comment by obscurerichard** [comment]
Thank you @ghewgill !

🏆 🎆 🥇 ⭐️
